package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _InteriorNode struct {
	bitfield _Bytes
	pointers _List__Pointer
}
type InteriorNode = *_InteriorNode

func (n _InteriorNode) FieldBitfield() Bytes {
	return &n.bitfield
}
func (n _InteriorNode) FieldPointers() List__Pointer {
	return &n.pointers
}

type _InteriorNode__Maybe struct {
	m schema.Maybe
	v InteriorNode
}
type MaybeInteriorNode = *_InteriorNode__Maybe

func (m MaybeInteriorNode) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeInteriorNode) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeInteriorNode) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeInteriorNode) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeInteriorNode) Must() InteriorNode {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var (
	fieldName__InteriorNode_Bitfield = _String{"bitfield"}
	fieldName__InteriorNode_Pointers = _String{"pointers"}
)
var _ ipld.Node = (InteriorNode)(&_InteriorNode{})
var _ schema.TypedNode = (InteriorNode)(&_InteriorNode{})

func (InteriorNode) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n InteriorNode) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "bitfield":
		return &n.bitfield, nil
	case "pointers":
		return &n.pointers, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n InteriorNode) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (InteriorNode) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"hamt.InteriorNode"}.LookupByIndex(0)
}
func (n InteriorNode) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n InteriorNode) MapIterator() ipld.MapIterator {
	return &_InteriorNode__MapItr{n, 0}
}

type _InteriorNode__MapItr struct {
	n   InteriorNode
	idx int
}

func (itr *_InteriorNode__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 2 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__InteriorNode_Bitfield
		v = &itr.n.bitfield
	case 1:
		k = &fieldName__InteriorNode_Pointers
		v = &itr.n.pointers
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_InteriorNode__MapItr) Done() bool {
	return itr.idx >= 2
}

func (InteriorNode) ListIterator() ipld.ListIterator {
	return nil
}
func (InteriorNode) Length() int {
	return 2
}
func (InteriorNode) IsAbsent() bool {
	return false
}
func (InteriorNode) IsNull() bool {
	return false
}
func (InteriorNode) AsBool() (bool, error) {
	return mixins.Map{"hamt.InteriorNode"}.AsBool()
}
func (InteriorNode) AsInt() (int, error) {
	return mixins.Map{"hamt.InteriorNode"}.AsInt()
}
func (InteriorNode) AsFloat() (float64, error) {
	return mixins.Map{"hamt.InteriorNode"}.AsFloat()
}
func (InteriorNode) AsString() (string, error) {
	return mixins.Map{"hamt.InteriorNode"}.AsString()
}
func (InteriorNode) AsBytes() ([]byte, error) {
	return mixins.Map{"hamt.InteriorNode"}.AsBytes()
}
func (InteriorNode) AsLink() (ipld.Link, error) {
	return mixins.Map{"hamt.InteriorNode"}.AsLink()
}
func (InteriorNode) Prototype() ipld.NodePrototype {
	return _InteriorNode__Prototype{}
}

type _InteriorNode__Prototype struct{}

func (_InteriorNode__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _InteriorNode__Builder
	nb.Reset()
	return &nb
}

type _InteriorNode__Builder struct {
	_InteriorNode__Assembler
}

func (nb *_InteriorNode__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_InteriorNode__Builder) Reset() {
	var w _InteriorNode
	var m schema.Maybe
	*nb = _InteriorNode__Builder{_InteriorNode__Assembler{w: &w, m: &m}}
}

type _InteriorNode__Assembler struct {
	w     *_InteriorNode
	m     *schema.Maybe
	state maState
	s     int
	f     int

	cm          schema.Maybe
	ca_bitfield _Bytes__Assembler
	ca_pointers _List__Pointer__Assembler
}

func (na *_InteriorNode__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_bitfield.reset()
	na.ca_pointers.reset()
}

var (
	fieldBit__InteriorNode_Bitfield    = 1 << 0
	fieldBit__InteriorNode_Pointers    = 1 << 1
	fieldBits__InteriorNode_sufficient = 0 + 1<<0 + 1<<1
)

func (na *_InteriorNode__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_InteriorNode{}
	}
	return na, nil
}
func (_InteriorNode__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"hamt.InteriorNode"}.BeginList(0)
}
func (na *_InteriorNode__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"hamt.InteriorNode"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_InteriorNode__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"hamt.InteriorNode"}.AssignBool(false)
}
func (_InteriorNode__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"hamt.InteriorNode"}.AssignInt(0)
}
func (_InteriorNode__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"hamt.InteriorNode"}.AssignFloat(0)
}
func (_InteriorNode__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"hamt.InteriorNode"}.AssignString("")
}
func (_InteriorNode__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"hamt.InteriorNode"}.AssignBytes(nil)
}
func (_InteriorNode__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"hamt.InteriorNode"}.AssignLink(nil)
}
func (na *_InteriorNode__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_InteriorNode); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "hamt.InteriorNode", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_InteriorNode__Assembler) Prototype() ipld.NodePrototype {
	return _InteriorNode__Prototype{}
}
func (ma *_InteriorNode__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_bitfield.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_pointers.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_InteriorNode__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "bitfield":
		if ma.s&fieldBit__InteriorNode_Bitfield != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__InteriorNode_Bitfield}
		}
		ma.s += fieldBit__InteriorNode_Bitfield
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_bitfield.w = &ma.w.bitfield
		ma.ca_bitfield.m = &ma.cm
		return &ma.ca_bitfield, nil
	case "pointers":
		if ma.s&fieldBit__InteriorNode_Pointers != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__InteriorNode_Pointers}
		}
		ma.s += fieldBit__InteriorNode_Pointers
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_pointers.w = &ma.w.pointers
		ma.ca_pointers.m = &ma.cm
		return &ma.ca_pointers, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName: "hamt.InteriorNode", Key: &_String{k}}
	}
}
func (ma *_InteriorNode__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_InteriorNode__KeyAssembler)(ma)
}
func (ma *_InteriorNode__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_bitfield.w = &ma.w.bitfield
		ma.ca_bitfield.m = &ma.cm
		return &ma.ca_bitfield
	case 1:
		ma.ca_pointers.w = &ma.w.pointers
		ma.ca_pointers.m = &ma.cm
		return &ma.ca_pointers
	default:
		panic("unreachable")
	}
}
func (ma *_InteriorNode__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_InteriorNode__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_InteriorNode__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}

type _InteriorNode__KeyAssembler _InteriorNode__Assembler

func (_InteriorNode__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.BeginMap(0)
}
func (_InteriorNode__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.BeginList(0)
}
func (na *_InteriorNode__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.AssignNull()
}
func (_InteriorNode__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.AssignBool(false)
}
func (_InteriorNode__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.AssignInt(0)
}
func (_InteriorNode__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.AssignFloat(0)
}
func (ka *_InteriorNode__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "bitfield":
		if ka.s&fieldBit__InteriorNode_Bitfield != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__InteriorNode_Bitfield}
		}
		ka.s += fieldBit__InteriorNode_Bitfield
		ka.state = maState_expectValue
		ka.f = 0
	case "pointers":
		if ka.s&fieldBit__InteriorNode_Pointers != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__InteriorNode_Pointers}
		}
		ka.s += fieldBit__InteriorNode_Pointers
		ka.state = maState_expectValue
		ka.f = 1
	default:
		return ipld.ErrInvalidKey{TypeName: "hamt.InteriorNode", Key: &_String{k}}
	}
	return nil
}
func (_InteriorNode__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.AssignBytes(nil)
}
func (_InteriorNode__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"hamt.InteriorNode.KeyAssembler"}.AssignLink(nil)
}
func (ka *_InteriorNode__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_InteriorNode__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (InteriorNode) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n InteriorNode) Representation() ipld.Node {
	return (*_InteriorNode__Repr)(n)
}

type _InteriorNode__Repr _InteriorNode

var _ ipld.Node = &_InteriorNode__Repr{}

func (_InteriorNode__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_InteriorNode__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"hamt.InteriorNode.Repr"}.LookupByString("")
}
func (n *_InteriorNode__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_InteriorNode__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.bitfield.Representation(), nil
	case 1:
		return n.pointers.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _InteriorNode__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "hamt.InteriorNode.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_InteriorNode__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_InteriorNode__Repr) ListIterator() ipld.ListIterator {
	return &_InteriorNode__ReprListItr{n, 0}
}

type _InteriorNode__ReprListItr struct {
	n   *_InteriorNode__Repr
	idx int
}

func (itr *_InteriorNode__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 2 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.bitfield.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.pointers.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_InteriorNode__ReprListItr) Done() bool {
	return itr.idx >= 2
}

func (rn *_InteriorNode__Repr) Length() int {
	l := 2
	return l
}
func (_InteriorNode__Repr) IsAbsent() bool {
	return false
}
func (_InteriorNode__Repr) IsNull() bool {
	return false
}
func (_InteriorNode__Repr) AsBool() (bool, error) {
	return mixins.List{"hamt.InteriorNode.Repr"}.AsBool()
}
func (_InteriorNode__Repr) AsInt() (int, error) {
	return mixins.List{"hamt.InteriorNode.Repr"}.AsInt()
}
func (_InteriorNode__Repr) AsFloat() (float64, error) {
	return mixins.List{"hamt.InteriorNode.Repr"}.AsFloat()
}
func (_InteriorNode__Repr) AsString() (string, error) {
	return mixins.List{"hamt.InteriorNode.Repr"}.AsString()
}
func (_InteriorNode__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"hamt.InteriorNode.Repr"}.AsBytes()
}
func (_InteriorNode__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"hamt.InteriorNode.Repr"}.AsLink()
}
func (_InteriorNode__Repr) Prototype() ipld.NodePrototype {
	return _InteriorNode__ReprPrototype{}
}

type _InteriorNode__ReprPrototype struct{}

func (_InteriorNode__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _InteriorNode__ReprBuilder
	nb.Reset()
	return &nb
}

type _InteriorNode__ReprBuilder struct {
	_InteriorNode__ReprAssembler
}

func (nb *_InteriorNode__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_InteriorNode__ReprBuilder) Reset() {
	var w _InteriorNode
	var m schema.Maybe
	*nb = _InteriorNode__ReprBuilder{_InteriorNode__ReprAssembler{w: &w, m: &m}}
}

type _InteriorNode__ReprAssembler struct {
	w     *_InteriorNode
	m     *schema.Maybe
	state laState
	f     int

	cm          schema.Maybe
	ca_bitfield _Bytes__ReprAssembler
	ca_pointers _List__Pointer__ReprAssembler
}

func (na *_InteriorNode__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_bitfield.reset()
	na.ca_pointers.reset()
}
func (_InteriorNode__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"hamt.InteriorNode.Repr"}.BeginMap(0)
}
func (na *_InteriorNode__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_InteriorNode{}
	}
	return na, nil
}
func (na *_InteriorNode__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"hamt.InteriorNode.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_InteriorNode__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"hamt.InteriorNode.Repr"}.AssignBool(false)
}
func (_InteriorNode__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"hamt.InteriorNode.Repr"}.AssignInt(0)
}
func (_InteriorNode__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"hamt.InteriorNode.Repr"}.AssignFloat(0)
}
func (_InteriorNode__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"hamt.InteriorNode.Repr"}.AssignString("")
}
func (_InteriorNode__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"hamt.InteriorNode.Repr"}.AssignBytes(nil)
}
func (_InteriorNode__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"hamt.InteriorNode.Repr"}.AssignLink(nil)
}
func (na *_InteriorNode__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_InteriorNode); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "hamt.InteriorNode.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_InteriorNode__ReprAssembler) Prototype() ipld.NodePrototype {
	return _InteriorNode__ReprPrototype{}
}
func (la *_InteriorNode__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_InteriorNode__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 2 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(2)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_bitfield.w = &la.w.bitfield
		la.ca_bitfield.m = &la.cm
		return &la.ca_bitfield
	case 1:
		la.ca_pointers.w = &la.w.pointers
		la.ca_pointers.m = &la.cm
		return &la.ca_pointers
	default:
		panic("unreachable")
	}
}
func (la *_InteriorNode__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_InteriorNode__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
