package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _KV struct {
	key   _Bytes
	value _Any
}
type KV = *_KV

func (n _KV) FieldKey() Bytes {
	return &n.key
}
func (n _KV) FieldValue() Any {
	return &n.value
}

type _KV__Maybe struct {
	m schema.Maybe
	v KV
}
type MaybeKV = *_KV__Maybe

func (m MaybeKV) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeKV) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeKV) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeKV) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeKV) Must() KV {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var (
	fieldName__KV_Key   = _String{"key"}
	fieldName__KV_Value = _String{"value"}
)
var _ ipld.Node = (KV)(&_KV{})
var _ schema.TypedNode = (KV)(&_KV{})

func (KV) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n KV) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "key":
		return &n.key, nil
	case "value":
		return &n.value, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n KV) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (KV) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"hamt.KV"}.LookupByIndex(0)
}
func (n KV) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n KV) MapIterator() ipld.MapIterator {
	return &_KV__MapItr{n, 0}
}

type _KV__MapItr struct {
	n   KV
	idx int
}

func (itr *_KV__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 2 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__KV_Key
		v = &itr.n.key
	case 1:
		k = &fieldName__KV_Value
		v = &itr.n.value
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_KV__MapItr) Done() bool {
	return itr.idx >= 2
}

func (KV) ListIterator() ipld.ListIterator {
	return nil
}
func (KV) Length() int {
	return 2
}
func (KV) IsAbsent() bool {
	return false
}
func (KV) IsNull() bool {
	return false
}
func (KV) AsBool() (bool, error) {
	return mixins.Map{"hamt.KV"}.AsBool()
}
func (KV) AsInt() (int, error) {
	return mixins.Map{"hamt.KV"}.AsInt()
}
func (KV) AsFloat() (float64, error) {
	return mixins.Map{"hamt.KV"}.AsFloat()
}
func (KV) AsString() (string, error) {
	return mixins.Map{"hamt.KV"}.AsString()
}
func (KV) AsBytes() ([]byte, error) {
	return mixins.Map{"hamt.KV"}.AsBytes()
}
func (KV) AsLink() (ipld.Link, error) {
	return mixins.Map{"hamt.KV"}.AsLink()
}
func (KV) Prototype() ipld.NodePrototype {
	return _KV__Prototype{}
}

type _KV__Prototype struct{}

func (_KV__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _KV__Builder
	nb.Reset()
	return &nb
}

type _KV__Builder struct {
	_KV__Assembler
}

func (nb *_KV__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_KV__Builder) Reset() {
	var w _KV
	var m schema.Maybe
	*nb = _KV__Builder{_KV__Assembler{w: &w, m: &m}}
}

type _KV__Assembler struct {
	w     *_KV
	m     *schema.Maybe
	state maState
	s     int
	f     int

	cm       schema.Maybe
	ca_key   _Bytes__Assembler
	ca_value _Any__Assembler
}

func (na *_KV__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_key.reset()
	na.ca_value.reset()
}

var (
	fieldBit__KV_Key         = 1 << 0
	fieldBit__KV_Value       = 1 << 1
	fieldBits__KV_sufficient = 0 + 1<<0 + 1<<1
)

func (na *_KV__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_KV{}
	}
	return na, nil
}
func (_KV__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"hamt.KV"}.BeginList(0)
}
func (na *_KV__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"hamt.KV"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_KV__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"hamt.KV"}.AssignBool(false)
}
func (_KV__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"hamt.KV"}.AssignInt(0)
}
func (_KV__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"hamt.KV"}.AssignFloat(0)
}
func (_KV__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"hamt.KV"}.AssignString("")
}
func (_KV__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"hamt.KV"}.AssignBytes(nil)
}
func (_KV__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"hamt.KV"}.AssignLink(nil)
}
func (na *_KV__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_KV); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "hamt.KV", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_KV__Assembler) Prototype() ipld.NodePrototype {
	return _KV__Prototype{}
}
func (ma *_KV__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_key.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_value.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_KV__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "key":
		if ma.s&fieldBit__KV_Key != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__KV_Key}
		}
		ma.s += fieldBit__KV_Key
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_key.w = &ma.w.key
		ma.ca_key.m = &ma.cm
		return &ma.ca_key, nil
	case "value":
		if ma.s&fieldBit__KV_Value != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__KV_Value}
		}
		ma.s += fieldBit__KV_Value
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_value.w = &ma.w.value
		ma.ca_value.m = &ma.cm
		return &ma.ca_value, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName: "hamt.KV", Key: &_String{k}}
	}
}
func (ma *_KV__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_KV__KeyAssembler)(ma)
}
func (ma *_KV__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_key.w = &ma.w.key
		ma.ca_key.m = &ma.cm
		return &ma.ca_key
	case 1:
		ma.ca_value.w = &ma.w.value
		ma.ca_value.m = &ma.cm
		return &ma.ca_value
	default:
		panic("unreachable")
	}
}
func (ma *_KV__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_KV__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_KV__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}

type _KV__KeyAssembler _KV__Assembler

func (_KV__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.BeginMap(0)
}
func (_KV__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.BeginList(0)
}
func (na *_KV__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.AssignNull()
}
func (_KV__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.AssignBool(false)
}
func (_KV__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.AssignInt(0)
}
func (_KV__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.AssignFloat(0)
}
func (ka *_KV__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "key":
		if ka.s&fieldBit__KV_Key != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__KV_Key}
		}
		ka.s += fieldBit__KV_Key
		ka.state = maState_expectValue
		ka.f = 0
	case "value":
		if ka.s&fieldBit__KV_Value != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__KV_Value}
		}
		ka.s += fieldBit__KV_Value
		ka.state = maState_expectValue
		ka.f = 1
	default:
		return ipld.ErrInvalidKey{TypeName: "hamt.KV", Key: &_String{k}}
	}
	return nil
}
func (_KV__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.AssignBytes(nil)
}
func (_KV__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"hamt.KV.KeyAssembler"}.AssignLink(nil)
}
func (ka *_KV__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_KV__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (KV) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n KV) Representation() ipld.Node {
	return (*_KV__Repr)(n)
}

type _KV__Repr _KV

var _ ipld.Node = &_KV__Repr{}

func (_KV__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_KV__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"hamt.KV.Repr"}.LookupByString("")
}
func (n *_KV__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_KV__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.key.Representation(), nil
	case 1:
		return n.value.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _KV__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "hamt.KV.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_KV__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_KV__Repr) ListIterator() ipld.ListIterator {
	return &_KV__ReprListItr{n, 0}
}

type _KV__ReprListItr struct {
	n   *_KV__Repr
	idx int
}

func (itr *_KV__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 2 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.key.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.value.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_KV__ReprListItr) Done() bool {
	return itr.idx >= 2
}

func (rn *_KV__Repr) Length() int {
	l := 2
	return l
}
func (_KV__Repr) IsAbsent() bool {
	return false
}
func (_KV__Repr) IsNull() bool {
	return false
}
func (_KV__Repr) AsBool() (bool, error) {
	return mixins.List{"hamt.KV.Repr"}.AsBool()
}
func (_KV__Repr) AsInt() (int, error) {
	return mixins.List{"hamt.KV.Repr"}.AsInt()
}
func (_KV__Repr) AsFloat() (float64, error) {
	return mixins.List{"hamt.KV.Repr"}.AsFloat()
}
func (_KV__Repr) AsString() (string, error) {
	return mixins.List{"hamt.KV.Repr"}.AsString()
}
func (_KV__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"hamt.KV.Repr"}.AsBytes()
}
func (_KV__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"hamt.KV.Repr"}.AsLink()
}
func (_KV__Repr) Prototype() ipld.NodePrototype {
	return _KV__ReprPrototype{}
}

type _KV__ReprPrototype struct{}

func (_KV__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _KV__ReprBuilder
	nb.Reset()
	return &nb
}

type _KV__ReprBuilder struct {
	_KV__ReprAssembler
}

func (nb *_KV__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_KV__ReprBuilder) Reset() {
	var w _KV
	var m schema.Maybe
	*nb = _KV__ReprBuilder{_KV__ReprAssembler{w: &w, m: &m}}
}

type _KV__ReprAssembler struct {
	w     *_KV
	m     *schema.Maybe
	state laState
	f     int

	cm       schema.Maybe
	ca_key   _Bytes__ReprAssembler
	ca_value _Any__ReprAssembler
}

func (na *_KV__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_key.reset()
	na.ca_value.reset()
}
func (_KV__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"hamt.KV.Repr"}.BeginMap(0)
}
func (na *_KV__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_KV{}
	}
	return na, nil
}
func (na *_KV__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"hamt.KV.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_KV__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"hamt.KV.Repr"}.AssignBool(false)
}
func (_KV__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"hamt.KV.Repr"}.AssignInt(0)
}
func (_KV__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"hamt.KV.Repr"}.AssignFloat(0)
}
func (_KV__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"hamt.KV.Repr"}.AssignString("")
}
func (_KV__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"hamt.KV.Repr"}.AssignBytes(nil)
}
func (_KV__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"hamt.KV.Repr"}.AssignLink(nil)
}
func (na *_KV__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_KV); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "hamt.KV.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_KV__ReprAssembler) Prototype() ipld.NodePrototype {
	return _KV__ReprPrototype{}
}
func (la *_KV__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_KV__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 2 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(2)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_key.w = &la.w.key
		la.ca_key.m = &la.cm
		return &la.ca_key
	case 1:
		la.ca_value.w = &la.w.value
		la.ca_value.m = &la.cm
		return &la.ca_value
	default:
		panic("unreachable")
	}
}
func (la *_KV__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_KV__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
