package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _Link__InteriorNode struct{ x ipld.Link }
type Link__InteriorNode = *_Link__InteriorNode

func (n Link__InteriorNode) Link() ipld.Link {
	return n.x
}
func (_Link__InteriorNode__Prototype) FromLink(v ipld.Link) (Link__InteriorNode, error) {
	n := _Link__InteriorNode{v}
	return &n, nil
}

type _Link__InteriorNode__Maybe struct {
	m schema.Maybe
	v Link__InteriorNode
}
type MaybeLink__InteriorNode = *_Link__InteriorNode__Maybe

func (m MaybeLink__InteriorNode) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLink__InteriorNode) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLink__InteriorNode) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLink__InteriorNode) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeLink__InteriorNode) Must() Link__InteriorNode {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var _ ipld.Node = (Link__InteriorNode)(&_Link__InteriorNode{})
var _ schema.TypedNode = (Link__InteriorNode)(&_Link__InteriorNode{})

func (Link__InteriorNode) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Link
}
func (Link__InteriorNode) LookupByString(string) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.LookupByString("")
}
func (Link__InteriorNode) LookupByNode(ipld.Node) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.LookupByNode(nil)
}
func (Link__InteriorNode) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.LookupByIndex(0)
}
func (Link__InteriorNode) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.LookupBySegment(seg)
}
func (Link__InteriorNode) MapIterator() ipld.MapIterator {
	return nil
}
func (Link__InteriorNode) ListIterator() ipld.ListIterator {
	return nil
}
func (Link__InteriorNode) Length() int {
	return -1
}
func (Link__InteriorNode) IsAbsent() bool {
	return false
}
func (Link__InteriorNode) IsNull() bool {
	return false
}
func (Link__InteriorNode) AsBool() (bool, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.AsBool()
}
func (Link__InteriorNode) AsInt() (int, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.AsInt()
}
func (Link__InteriorNode) AsFloat() (float64, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.AsFloat()
}
func (Link__InteriorNode) AsString() (string, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.AsString()
}
func (Link__InteriorNode) AsBytes() ([]byte, error) {
	return mixins.Link{"hamt.Link__InteriorNode"}.AsBytes()
}
func (n Link__InteriorNode) AsLink() (ipld.Link, error) {
	return n.x, nil
}
func (Link__InteriorNode) Prototype() ipld.NodePrototype {
	return _Link__InteriorNode__Prototype{}
}

type _Link__InteriorNode__Prototype struct{}

func (_Link__InteriorNode__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _Link__InteriorNode__Builder
	nb.Reset()
	return &nb
}

type _Link__InteriorNode__Builder struct {
	_Link__InteriorNode__Assembler
}

func (nb *_Link__InteriorNode__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Link__InteriorNode__Builder) Reset() {
	var w _Link__InteriorNode
	var m schema.Maybe
	*nb = _Link__InteriorNode__Builder{_Link__InteriorNode__Assembler{w: &w, m: &m}}
}

type _Link__InteriorNode__Assembler struct {
	w *_Link__InteriorNode
	m *schema.Maybe
}

func (na *_Link__InteriorNode__Assembler) reset() {}
func (_Link__InteriorNode__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.BeginMap(0)
}
func (_Link__InteriorNode__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.BeginList(0)
}
func (na *_Link__InteriorNode__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	panic("unreachable")
}
func (_Link__InteriorNode__Assembler) AssignBool(bool) error {
	return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.AssignBool(false)
}
func (_Link__InteriorNode__Assembler) AssignInt(int) error {
	return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.AssignInt(0)
}
func (_Link__InteriorNode__Assembler) AssignFloat(float64) error {
	return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.AssignFloat(0)
}
func (_Link__InteriorNode__Assembler) AssignString(string) error {
	return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.AssignString("")
}
func (_Link__InteriorNode__Assembler) AssignBytes([]byte) error {
	return mixins.LinkAssembler{"hamt.Link__InteriorNode"}.AssignBytes(nil)
}
func (na *_Link__InteriorNode__Assembler) AssignLink(v ipld.Link) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	if na.w == nil {
		na.w = &_Link__InteriorNode{}
	}
	na.w.x = v
	*na.m = schema.Maybe_Value
	return nil
}
func (na *_Link__InteriorNode__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Link__InteriorNode); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v2, err := v.AsLink(); err != nil {
		return err
	} else {
		return na.AssignLink(v2)
	}
}
func (_Link__InteriorNode__Assembler) Prototype() ipld.NodePrototype {
	return _Link__InteriorNode__Prototype{}
}
func (Link__InteriorNode) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n Link__InteriorNode) Representation() ipld.Node {
	return (*_Link__InteriorNode__Repr)(n)
}

type _Link__InteriorNode__Repr = _Link__InteriorNode

var _ ipld.Node = &_Link__InteriorNode__Repr{}

type _Link__InteriorNode__ReprPrototype = _Link__InteriorNode__Prototype
type _Link__InteriorNode__ReprAssembler = _Link__InteriorNode__Assembler
