package hamt

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _List__Pointer struct {
	x []_Pointer
}
type List__Pointer = *_List__Pointer
type _List__Pointer__Maybe struct {
	m schema.Maybe
	v List__Pointer
}
type MaybeList__Pointer = *_List__Pointer__Maybe

func (m MaybeList__Pointer) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeList__Pointer) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeList__Pointer) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeList__Pointer) AsNode() ipld.Node {
	switch m.m {
	case schema.Maybe_Absent:
		return ipld.Absent
	case schema.Maybe_Null:
		return ipld.Null
	case schema.Maybe_Value:
		return m.v
	default:
		panic("unreachable")
	}
}
func (m MaybeList__Pointer) Must() List__Pointer {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}

var _ ipld.Node = (List__Pointer)(&_List__Pointer{})
var _ schema.TypedNode = (List__Pointer)(&_List__Pointer{})

func (List__Pointer) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (List__Pointer) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"hamt.List__Pointer"}.LookupByString("")
}
func (n List__Pointer) LookupByNode(k ipld.Node) (ipld.Node, error) {
	idx, err := k.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(idx)
}
func (n List__Pointer) LookupByIndex(idx int) (ipld.Node, error) {
	if n.Length() <= idx {
		return nil, ipld.ErrNotExists{ipld.PathSegmentOfInt(idx)}
	}
	v := &n.x[idx]
	return v, nil
}
func (n List__Pointer) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "hamt.List__Pointer", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (List__Pointer) MapIterator() ipld.MapIterator {
	return nil
}
func (n List__Pointer) ListIterator() ipld.ListIterator {
	return &_List__Pointer__ListItr{n, 0}
}

type _List__Pointer__ListItr struct {
	n   List__Pointer
	idx int
}

func (itr *_List__Pointer__ListItr) Next() (idx int, v ipld.Node, _ error) {
	if itr.idx >= len(itr.n.x) {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	idx = itr.idx
	x := &itr.n.x[itr.idx]
	v = x
	itr.idx++
	return
}
func (itr *_List__Pointer__ListItr) Done() bool {
	return itr.idx >= len(itr.n.x)
}

func (n List__Pointer) Length() int {
	return len(n.x)
}
func (List__Pointer) IsAbsent() bool {
	return false
}
func (List__Pointer) IsNull() bool {
	return false
}
func (List__Pointer) AsBool() (bool, error) {
	return mixins.List{"hamt.List__Pointer"}.AsBool()
}
func (List__Pointer) AsInt() (int, error) {
	return mixins.List{"hamt.List__Pointer"}.AsInt()
}
func (List__Pointer) AsFloat() (float64, error) {
	return mixins.List{"hamt.List__Pointer"}.AsFloat()
}
func (List__Pointer) AsString() (string, error) {
	return mixins.List{"hamt.List__Pointer"}.AsString()
}
func (List__Pointer) AsBytes() ([]byte, error) {
	return mixins.List{"hamt.List__Pointer"}.AsBytes()
}
func (List__Pointer) AsLink() (ipld.Link, error) {
	return mixins.List{"hamt.List__Pointer"}.AsLink()
}
func (List__Pointer) Prototype() ipld.NodePrototype {
	return _List__Pointer__Prototype{}
}

type _List__Pointer__Prototype struct{}

func (_List__Pointer__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _List__Pointer__Builder
	nb.Reset()
	return &nb
}

type _List__Pointer__Builder struct {
	_List__Pointer__Assembler
}

func (nb *_List__Pointer__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_List__Pointer__Builder) Reset() {
	var w _List__Pointer
	var m schema.Maybe
	*nb = _List__Pointer__Builder{_List__Pointer__Assembler{w: &w, m: &m}}
}

type _List__Pointer__Assembler struct {
	w     *_List__Pointer
	m     *schema.Maybe
	state laState

	cm schema.Maybe
	va _Pointer__Assembler
}

func (na *_List__Pointer__Assembler) reset() {
	na.state = laState_initial
	na.va.reset()
}
func (_List__Pointer__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"hamt.List__Pointer"}.BeginMap(0)
}
func (na *_List__Pointer__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if sizeHint < 0 {
		sizeHint = 0
	}
	if na.w == nil {
		na.w = &_List__Pointer{}
	}
	if sizeHint > 0 {
		na.w.x = make([]_Pointer, 0, sizeHint)
	}
	return na, nil
}
func (na *_List__Pointer__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"hamt.List__Pointer"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_List__Pointer__Assembler) AssignBool(bool) error {
	return mixins.ListAssembler{"hamt.List__Pointer"}.AssignBool(false)
}
func (_List__Pointer__Assembler) AssignInt(int) error {
	return mixins.ListAssembler{"hamt.List__Pointer"}.AssignInt(0)
}
func (_List__Pointer__Assembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"hamt.List__Pointer"}.AssignFloat(0)
}
func (_List__Pointer__Assembler) AssignString(string) error {
	return mixins.ListAssembler{"hamt.List__Pointer"}.AssignString("")
}
func (_List__Pointer__Assembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"hamt.List__Pointer"}.AssignBytes(nil)
}
func (_List__Pointer__Assembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"hamt.List__Pointer"}.AssignLink(nil)
}
func (na *_List__Pointer__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_List__Pointer); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "hamt.List__Pointer", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_List__Pointer__Assembler) Prototype() ipld.NodePrototype {
	return _List__Pointer__Prototype{}
}
func (la *_List__Pointer__Assembler) valueFinishTidy() bool {
	switch la.cm {
	case schema.Maybe_Value:
		la.va.w = nil
		la.cm = schema.Maybe_Absent
		la.state = laState_initial
		la.va.reset()
		return true
	default:
		return false
	}
}
func (la *_List__Pointer__Assembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	la.w.x = append(la.w.x, _Pointer{})
	la.state = laState_midValue
	row := &la.w.x[len(la.w.x)-1]
	la.va.w = row
	la.va.m = &la.cm
	return &la.va
}
func (la *_List__Pointer__Assembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_List__Pointer__Assembler) ValuePrototype(_ int) ipld.NodePrototype {
	return _Pointer__Prototype{}
}
func (List__Pointer) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n List__Pointer) Representation() ipld.Node {
	return (*_List__Pointer__Repr)(n)
}

type _List__Pointer__Repr _List__Pointer

var _ ipld.Node = &_List__Pointer__Repr{}

func (_List__Pointer__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_List__Pointer__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"hamt.List__Pointer.Repr"}.LookupByString("")
}
func (nr *_List__Pointer__Repr) LookupByNode(k ipld.Node) (ipld.Node, error) {
	v, err := (List__Pointer)(nr).LookupByNode(k)
	if err != nil || v == ipld.Null {
		return v, err
	}
	return v.(Pointer).Representation(), nil
}
func (nr *_List__Pointer__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	v, err := (List__Pointer)(nr).LookupByIndex(idx)
	if err != nil || v == ipld.Null {
		return v, err
	}
	return v.(Pointer).Representation(), nil
}
func (n _List__Pointer__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "hamt.List__Pointer.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_List__Pointer__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (nr *_List__Pointer__Repr) ListIterator() ipld.ListIterator {
	return &_List__Pointer__ReprListItr{(List__Pointer)(nr), 0}
}

type _List__Pointer__ReprListItr _List__Pointer__ListItr

func (itr *_List__Pointer__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	idx, v, err = (*_List__Pointer__ListItr)(itr).Next()
	if err != nil || v == ipld.Null {
		return
	}
	return idx, v.(Pointer).Representation(), nil
}
func (itr *_List__Pointer__ReprListItr) Done() bool {
	return (*_List__Pointer__ListItr)(itr).Done()
}

func (rn *_List__Pointer__Repr) Length() int {
	return len(rn.x)
}
func (_List__Pointer__Repr) IsAbsent() bool {
	return false
}
func (_List__Pointer__Repr) IsNull() bool {
	return false
}
func (_List__Pointer__Repr) AsBool() (bool, error) {
	return mixins.List{"hamt.List__Pointer.Repr"}.AsBool()
}
func (_List__Pointer__Repr) AsInt() (int, error) {
	return mixins.List{"hamt.List__Pointer.Repr"}.AsInt()
}
func (_List__Pointer__Repr) AsFloat() (float64, error) {
	return mixins.List{"hamt.List__Pointer.Repr"}.AsFloat()
}
func (_List__Pointer__Repr) AsString() (string, error) {
	return mixins.List{"hamt.List__Pointer.Repr"}.AsString()
}
func (_List__Pointer__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"hamt.List__Pointer.Repr"}.AsBytes()
}
func (_List__Pointer__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"hamt.List__Pointer.Repr"}.AsLink()
}
func (_List__Pointer__Repr) Prototype() ipld.NodePrototype {
	return _List__Pointer__ReprPrototype{}
}

type _List__Pointer__ReprPrototype struct{}

func (_List__Pointer__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _List__Pointer__ReprBuilder
	nb.Reset()
	return &nb
}

type _List__Pointer__ReprBuilder struct {
	_List__Pointer__ReprAssembler
}

func (nb *_List__Pointer__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_List__Pointer__ReprBuilder) Reset() {
	var w _List__Pointer
	var m schema.Maybe
	*nb = _List__Pointer__ReprBuilder{_List__Pointer__ReprAssembler{w: &w, m: &m}}
}

type _List__Pointer__ReprAssembler struct {
	w     *_List__Pointer
	m     *schema.Maybe
	state laState

	cm schema.Maybe
	va _Pointer__ReprAssembler
}

func (na *_List__Pointer__ReprAssembler) reset() {
	na.state = laState_initial
	na.va.reset()
}
func (_List__Pointer__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"hamt.List__Pointer.Repr"}.BeginMap(0)
}
func (na *_List__Pointer__ReprAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if sizeHint < 0 {
		sizeHint = 0
	}
	if na.w == nil {
		na.w = &_List__Pointer{}
	}
	if sizeHint > 0 {
		na.w.x = make([]_Pointer, 0, sizeHint)
	}
	return na, nil
}
func (na *_List__Pointer__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"hamt.List__Pointer.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_List__Pointer__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"hamt.List__Pointer.Repr"}.AssignBool(false)
}
func (_List__Pointer__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"hamt.List__Pointer.Repr"}.AssignInt(0)
}
func (_List__Pointer__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"hamt.List__Pointer.Repr"}.AssignFloat(0)
}
func (_List__Pointer__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"hamt.List__Pointer.Repr"}.AssignString("")
}
func (_List__Pointer__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"hamt.List__Pointer.Repr"}.AssignBytes(nil)
}
func (_List__Pointer__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"hamt.List__Pointer.Repr"}.AssignLink(nil)
}
func (na *_List__Pointer__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_List__Pointer); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "hamt.List__Pointer.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_List__Pointer__ReprAssembler) Prototype() ipld.NodePrototype {
	return _List__Pointer__ReprPrototype{}
}
func (la *_List__Pointer__ReprAssembler) valueFinishTidy() bool {
	switch la.cm {
	case schema.Maybe_Value:
		la.va.w = nil
		la.cm = schema.Maybe_Absent
		la.state = laState_initial
		la.va.reset()
		return true
	default:
		return false
	}
}
func (la *_List__Pointer__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	la.w.x = append(la.w.x, _Pointer{})
	la.state = laState_midValue
	row := &la.w.x[len(la.w.x)-1]
	la.va.w = row
	la.va.m = &la.cm
	return &la.va
}
func (la *_List__Pointer__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_List__Pointer__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	return _Pointer__ReprPrototype{}
}
